/*
 * Copyright 2026 DendyGrobovshik
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
plugins {
    alias(libs.plugins.androidLibrary)
    alias(libs.plugins.composeCompiler)
}

kotlin {
    compilerOptions {
        jvmTarget = org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_11
    }
}

android {
    namespace = "com.example.kernel.bridge"
    compileSdk = libs.versions.android.compileSdk.get().toInt()

    sourceSets.getByName("main") {
        // Host-side widget entries generated by the kernel compiler plugin.
        kotlin.srcDir("${rootProject.projectDir}/kernel/build/generated/rdma/widget-kotlin")
    }

    defaultConfig {
        minSdk = libs.versions.android.minSdk.get().toInt()
        externalNativeBuild {
            cmake {
                arguments("-DANDROID_STL=c++_shared")
            }
        }
    }

    externalNativeBuild {
        cmake {
            path("src/main/cpp/CMakeLists.txt")
        }
    }

    buildFeatures {
        prefab = true
    }
}

// Copy the user-generated C++ (classes/functions/widgets) out of the kernel build
// output into this module's native source tree. The generic RdmaComposerProxy is
// excluded: it belongs to the framework runtime.
val cleanGeneratedCpp = tasks.register<Delete>("cleanGeneratedCpp") {
    delete(fileTree("src/main/cpp/generated").matching {
        include("*.h", "*.cpp")
    })
}

val copyGeneratedCpp = tasks.register<Copy>("copyGeneratedCpp") {
    dependsOn(":kernel:compileKotlinJvm", cleanGeneratedCpp)
    from("${rootProject.projectDir}/kernel/build/generated/rdma/cpp")
    into("src/main/cpp/generated")
    include("*.h", "*.cpp")
    exclude("RdmaComposerProxy.h", "RdmaComposerProxy.cpp")
}

val invalidateCmake = tasks.register<Delete>("invalidateCmake") {
    dependsOn(copyGeneratedCpp)
    delete(".cxx")
}

tasks.whenTaskAdded {
    if (name.startsWith("configureCMake")) {
        dependsOn(invalidateCmake)
    }
}

dependencies {
    implementation(project(":kernel"))
    implementation(project(":rdma-runtime-android"))
    implementation(libs.compose.runtime)
    implementation(libs.hermes.android)
}
