package io.github.dendygrobovshik.kardman.plugin

import org.gradle.api.Project
import org.gradle.api.provider.Provider
import org.jetbrains.kotlin.gradle.plugin.KotlinCompilation
import org.jetbrains.kotlin.gradle.plugin.KotlinCompilerPluginSupportPlugin
import org.jetbrains.kotlin.gradle.plugin.KotlinPlatformType
import org.jetbrains.kotlin.gradle.plugin.SubpluginArtifact
import org.jetbrains.kotlin.gradle.plugin.SubpluginOption
import java.io.File

private const val RDMA_RUNTIME_BRIDGE_SOURCE = """package com.example.plugin

import androidx.compose.runtime.Composable
import androidx.compose.runtime.Composer
import androidx.compose.runtime.MutableState
import kotlin.js.unsafeCast

external object RDMA {
    fun registerContent(content: dynamic)
    fun setComposerEmpty(empty: Any)
    fun mutableStateOf(value: dynamic): dynamic
    fun registerBlock(block: dynamic): dynamic
}

fun rdmaMutableStateOf(value: Int): MutableState<Int> =
    RDMA.mutableStateOf(value).unsafeCast<MutableState<Int>>()

fun rdmaMutableStateOf(value: Boolean): MutableState<Boolean> =
    RDMA.mutableStateOf(value).unsafeCast<MutableState<Boolean>>()

fun rdmaMutableStateOf(value: String): MutableState<String> =
    RDMA.mutableStateOf(value).unsafeCast<MutableState<String>>()

fun rdmaRunApp(content: @Composable () -> Unit) {
    RDMA.setComposerEmpty(Composer.Companion.Empty)
    RDMA.registerContent(content)
}
"""

class RdmaPluginGradlePlugin : KotlinCompilerPluginSupportPlugin {

    override fun apply(target: Project) {
        // Static guest-side bridge (external RDMA object + generic protocol helpers).
        // Per-widget `rdmaXxx` proxies are generated by the compiler plugin into
        // `RdmaWidgetBridge.kt`.
        val dir = File(target.buildDir, "generated/rdma")
        dir.mkdirs()
        File(dir, "RdmaRuntimeBridge.kt").writeText(RDMA_RUNTIME_BRIDGE_SOURCE)
    }

    override fun isApplicable(kotlinCompilation: KotlinCompilation<*>): Boolean =
        kotlinCompilation.platformType == KotlinPlatformType.jvm

    override fun getCompilerPluginId(): String = "rdma-plugin-compiler-plugin"

    override fun getPluginArtifact(): SubpluginArtifact =
        SubpluginArtifact("io.github.dendygrobovshik.kardman", "rdma-plugin-compiler-plugin", "1.0")

    override fun applyToCompilation(kotlinCompilation: KotlinCompilation<*>): Provider<List<SubpluginOption>> {
        val project = kotlinCompilation.project
        return project.provider {
            val manifestPath = (project.findProperty("rdmaManifest") as? String)
                ?: "${project.rootProject.projectDir}/kernel/build/generated/rdma/rdma_manifest.json"
            val outputDir = "${project.buildDir}/generated/rdma"
            listOf(
                SubpluginOption("rdmaManifest", manifestPath),
                SubpluginOption("rdmaOutputDir", outputDir),
            )
        }
    }
}
